from __future__ import annotations
import argparse,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
TREES=[('primary',ROOT/'.local'/'skills'),('secondary',ROOT/'.local'/'secondary_skills')]
INDEX=ROOT/'.local'/'skill-index.md'
AGENTS=ROOT/'AGENTS.md'
WINDSURF=ROOT/'.windsurf'/'rules'/'agent-context.md'
LEGACY={'renamed':[('code_review','code-review'),('repl_setup','local-dev-setup'),('security_scan','security-scan'),('threat_modeling','threat-modeling'),('repl-seo-optimizer','launch-seo-optimizer')],'moved':[('media-generation','.local/skills/media-generation','.local/secondary_skills/media-generation'),('slides','.local/skills/slides','.local/secondary_skills/slides'),('react-vite','.local/skills/react-vite','.local/secondary_skills/react-vite'),('package-management','.local/skills/package-management','.local/secondary_skills/package-management'),('web-search','.local/skills/web-search','.local/secondary_skills/web-search')],'deleted':['mockup-sandbox','mockup-extract','mockup-graduate','project_tasks','replit-docs','agent-inbox','integrations','external_apis','query-integration-data','post_merge_setup']}
BANNED=['replit','REPLIT_','.replit','subrepl','proposeIntegration','addIntegration','configureWorkflow','createArtifact','suggestDeploy','get_canvas_state','focus_canvas_shapes','{{skill(','.replit.dev']
LINK=re.compile(r'\[[^\]]+\]\(([^)]+)\)')
REF=re.compile(r'(?<![A-Za-z0-9_.-])(?:\./)?(?:references|scripts|assets|agents)/[A-Za-z0-9._/-]+')
FRONT=re.compile(r'^---\r?\n(.*?)\r?\n---\r?\n?(.*)$',re.S)
HYPHEN=re.compile(r'^[a-z0-9]+(?:-[a-z0-9]+)*$')
TEXT={'.md','.txt','.yaml','.yml','.json','.py','.js','.ts','.tsx','.css','.html'}

def parse_skill(path:Path):
    m=FRONT.match(path.read_text(encoding='utf-8'))
    if not m: raise ValueError(f'missing or invalid frontmatter in {path}')
    data={}
    for line in m.group(1).splitlines():
        if not line.strip(): continue
        if ':' not in line: raise ValueError(f'invalid frontmatter line in {path}: {line}')
        k,v=line.split(':',1); data[k.strip()]=v.strip().strip('"').strip("'")
    return data,m.group(2)

def parse_openai(path:Path):
    text=path.read_text(encoding='utf-8')
    out={}
    for key in ('display_name','short_description','default_prompt'):
        m=re.search(rf'^\s*{key}:\s*\"(.+)\"\s*$',text,re.M)
        if not m: raise ValueError(f'missing {key} in {path}')
        out[key]=m.group(1)
    if not re.search(r'^\s*allow_implicit_invocation:\s*true\s*$',text,re.M): raise ValueError(f'missing allow_implicit_invocation: true in {path}')
    return out

def build_index():
    lines=['# Skill Index','','This file is generated by `python scripts/validate_skill_catalog.py --write-index`.','','The canonical skill catalogs live in `.local/skills` and `.local/secondary_skills`.','There is no mirrored host-specific skill tree. Hosts should read the canonical markdown in place.','']
    for label,tree in TREES:
        lines+=[f'## {label.title()} Skills','']
        for d in sorted(p for p in tree.iterdir() if p.is_dir()):
            fm,_=parse_skill(d/'SKILL.md')
            lines.append(f'- `{d.name}`: {fm["description"]} Path: `{(tree.relative_to(ROOT)/d.name).as_posix()}`')
        lines.append('')
    lines+=['## Legacy Mapping','','### Renamed','']+[f'- `{a}` -> `{b}`' for a,b in LEGACY['renamed']]+['','### Moved From Primary To Secondary','']+[f'- `{n}`: `{old}` -> `{new}`' for n,old,new in LEGACY['moved']]+['','### Deleted','']+[f'- `{n}`' for n in LEGACY['deleted']]+['','### Registry Notes','','- `.local/skills` remains the tight 4tie-owned catalog for repo work.','- `.local/secondary_skills` remains the portable extras catalog.','- Each surviving skill folder contains `SKILL.md` plus `agents/openai.yaml`.']
    return '\n'.join(lines).strip()+'\n'

def resolve_local(file,target):
    local=(file.parent/target).resolve()
    if local.exists(): return local
    m=re.search(r'(references|scripts|assets|agents)/',target)
    if m:
        repo=(ROOT/target[m.start():]).resolve()
        if repo.exists(): return repo
    return local

def validate_links(errs,file):
    text=file.read_text(encoding='utf-8')
    for rx in (LINK,REF):
        for m in rx.finditer(text):
            t=m.group(1) if rx is LINK else m.group(0)
            if rx is LINK and (not t or t.startswith(('http://','https://','#','mailto:'))): continue
            if not resolve_local(file,t).exists(): errs.append(f'broken reference in {file}: {t}')

def validate_skill_dir(errs,d):
    if not HYPHEN.fullmatch(d.name): errs.append(f'skill directory is not hyphen-case: {d}')
    sf=d/'SKILL.md'; of=d/'agents'/'openai.yaml'
    if not sf.exists(): errs.append(f'missing SKILL.md in {d}'); return
    if not of.exists(): errs.append(f'missing agents/openai.yaml in {d}')
    try:
        fm,_=parse_skill(sf)
        if set(fm)!={'name','description'}: errs.append(f'frontmatter keys must be exactly name and description in {sf}')
        if fm.get('name')!=d.name: errs.append(f'frontmatter name mismatch in {sf}: {fm.get("name")} vs {d.name}')
        if not fm.get('description','').strip(): errs.append(f'missing description in {sf}')
    except Exception as e: errs.append(str(e))
    if of.exists():
        try:
            meta=parse_openai(of)
            if f'${d.name}' not in meta['default_prompt']: errs.append(f'default_prompt must mention ${d.name} in {of}')
        except Exception as e: errs.append(str(e))
    for f in d.rglob('*'):
        if f.is_file() and f.suffix.lower() in {'.md','.txt','.yaml','.yml'}: validate_links(errs,f)
        if f.is_file() and f.suffix.lower() in TEXT:
            txt=f.read_text(encoding='utf-8',errors='ignore')
            for marker in BANNED:
                if marker in txt: errs.append(f"banned marker '{marker}' found in {f}")

def main():
    ap=argparse.ArgumentParser(description='Validate the repo skill catalog.')
    ap.add_argument('--write-index',action='store_true',help='Regenerate .local/skill-index.md before validation')
    a=ap.parse_args()
    if a.write_index: INDEX.write_text(build_index(),encoding='utf-8')
    errs=[]
    for _,tree in TREES:
        for d in sorted(p for p in tree.iterdir() if p.is_dir()): validate_skill_dir(errs,d)
    for p in (AGENTS,WINDSURF,INDEX):
        if not p.exists(): errs.append(f'missing {p}')
    if INDEX.exists() and INDEX.read_text(encoding='utf-8')!=build_index(): errs.append(f'{INDEX} is out of date. Re-run with --write-index')
    if errs:
        print('Skill catalog validation failed:')
        [print(f'- {e}') for e in errs]
        raise SystemExit(1)
    print('Skill catalog validation passed.')
if __name__=='__main__': main()
